config/routes.rb
Rails.application.routes.draw do

  resources :items, only: [:index]

  resources :customers

  root 'welcome#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :guid

  def guid
    # only if it doesn't exist already?
    if session[:guid].blank?
      session[:guid] = SecureRandom.urlsafe_base64
    end
    return session[:guid]
  end

  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
    payload[:guid] = guid
    payload[:env] = Rails.env.to_s
    payload[:level] = Rails.logger.level

  end
end

app/controllers/customers_controller.rb
require 'rest-client'

class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show

    # TODO: get the squareup customer
    #@customer.squareup_customer_id



  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|

      # save rails customer
      ActiveRecord::Base.transaction do
        if @customer.save

          # taking customer data and posting it to squareup
          squareup_customer_id = create_squareup_customer({
            "given_name": @customer.given_name,
            "family_name": @customer.family_name,
            "email_address": @customer.email_address,
            "phone_number": @customer.phone_number,
            "address": {
              "address_line_1": @customer.address_line_1,
              "address_line_2": @customer.address_line_2,
              "locality": '',
              "administrative_district_level_1": '',
              "postal_code": @customer.postal_code,
              "country": @customer.country
            },
            "reference_id": '',
            "note": ''
          })
          @customer.update_attributes(squareup_customer_id: squareup_customer_id)

          format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
          format.json { render :show, status: :created, location: @customer }
        else
          format.html { render :new }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:given_name, :family_name, :email_address, :address, :address_line_1, :address_line_2, :locality, :administrative_district_level_1, :postal_code, :country, :phone_number, :reference_id, :note)
    end

    def create_squareup_customer(customer_hash)
      begin
        headers = {:Authorization => SQUAREUP_CONFIG['auth'], accept: :json}
        response = RestClient.post 'https://connect.squareup.com/v2/customers', customer_hash.to_json, headers
        squareup_customer = JSON.parse(response)
        return squareup_customer['customer']['id']
      rescue => e
        Rails.logger.error e.inspect
        raise
      end

    end
end

app/controllers/items_controller.rb
require 'rest-client'

class ItemsController < ApplicationController
  def index
    location = get_squareup_location
    @items = get_squareup_items(location['id'])
  end

  private

    def get_squareup_location
      headers = {:Authorization => SQUAREUP_CONFIG['auth'], accept: :json}
      response = RestClient.get "https://connect.squareup.com/v2/locations", headers
      return JSON.parse(response)['locations'].first
    end

    def get_squareup_items(location_id)
      begin
        headers = {:Authorization => SQUAREUP_CONFIG['auth'], accept: :json}
        response = RestClient.get "https://connect.squareup.com/v1/#{location_id}/items", headers
        return JSON.parse(response)
      rescue => e
        Rails.logger.error e.inspect
        raise
      end

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'First Name' %><br>
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label 'Last name' %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :address_line_1 %><br>
    <%= f.text_field :address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :address_line_2 %><br>
    <%= f.text_field :address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Postal code</th>
      <th>Country</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.given_name %></td>
        <td><%= customer.family_name %></td>
        <td><%= customer.email_address %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.country %></td>
        <td><%= customer.phone_number %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @customer.given_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @customer.family_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @customer.email_address %>
</p>


<p>
  <strong>Address line 1:</strong>
  <%= @customer.address_line_1 %>
</p>

<p>
  <strong>Address line 2:</strong>
  <%= @customer.address_line_2 %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @customer.postal_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @customer.country %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <h1><%= item['name'] %><h1>
  <p><%= item['description'] %></p>
  <p><%= image_tag item['master_image']['url'] %></p>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Customers</title>

  <!-- Always force latest IE rendering engine or request Chrome Frame -->
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

 <header class="site-header">
  <nav class="site-nav container" role="navigation">
      <%= link_to '/', class: 'navbar-brand' do %>
        Customers
      <% end %>

      <ul class="nav-links">
        <li><%= link_to 'Customers', customers_path %>
          <ul></ul>
        </li>
        <li><%= link_to 'Items', items_path %>
          <ul></ul>
        </li>
      </ul>
      </div>
      <div class="mobile-menu"><i class="fa fa-navicon"></i></div>

    </nav>

  </div>
</header>

<main class="site-main">
  <div class="container module">
    <%= yield %>
  </div>
</main>

<footer class="site-footer">
  <div class="container">
    <p>&copy; <%= Time.now.year %> <a href="/">Customers App</a></p>
  </div>
</footer>

  <!-- bottom  -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :js %>
  <% if Rails.env == "Production" %><!-- ex. google analytics --><% end %>
  <!-- /bottom  -->
</body>
</html>

app/views/welcome/index.html.erb
<h2>Customers App Demo</h2>